# Generated by Django 4.1.7 on 2023-04-27 21:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Enter alt text for image', max_length=255, null=True, verbose_name='alt text'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_feature',
            field=models.BooleanField(default=False, help_text='feature image', verbose_name='feature image'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, default='images/default.png', help_text='Upload a product image', null=True, upload_to='images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='products.product'),
        ),
    ]
